# Generated by Django 5.1.3 on 2025-02-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Davlati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetelsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GuruhgaOid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HisobSababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JismoniyShaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfl_raqami', models.CharField(blank=True, max_length=100, null=True)),
                ('pasport_seriya', models.CharField(blank=True, max_length=100, null=True)),
                ('pasport_raqam', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nomlanishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rangi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rusumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TashkilotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='XujjatTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Xususiyatlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetelsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detal_modeli', models.CharField(max_length=100)),
                ('detal_seriyasi', models.CharField(max_length=100)),
                ('detal_raqami', models.CharField(max_length=100)),
                ('detal_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detelname')),
            ],
        ),
        migrations.CreateModel(
            name='JinoyatIshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.band')),
                ('modda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modda')),
                ('qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qism')),
            ],
        ),
        migrations.CreateModel(
            name='JinoyatRegistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjat_turi', models.CharField(choices=[('material', 'Material/Protokol'), ('jinoyat', 'Jinoyat ishi')], max_length=10)),
                ('material_raqami', models.CharField(max_length=100)),
                ('hisob_sababi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hisobsababi')),
                ('jinoyat_ishi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jinoyatishi')),
            ],
        ),
        migrations.CreateModel(
            name='Fabula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoqotish_tavsifi', models.TextField()),
                ('yoqotilgan_sana', models.DateField()),
                ('yoqotilgan_joy', models.CharField(max_length=255)),
                ('yoqotilgan_mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahalla')),
                ('yoqotilgan_tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tuman')),
                ('yoqotilgan_viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='YuridikShaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashkilot_nomi', models.CharField(max_length=255)),
                ('kocha', models.CharField(max_length=255)),
                ('uy', models.CharField(max_length=50)),
                ('korpus', models.CharField(blank=True, max_length=50, null=True)),
                ('xonadon', models.CharField(blank=True, max_length=50, null=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahalla')),
                ('mamlakat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.davlat')),
                ('tashkilot_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tashkilotturi')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tuman')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='BuyumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriya', models.CharField(max_length=100)),
                ('raqam', models.CharField(max_length=100)),
                ('soni', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('zavod_firma', models.CharField(max_length=100)),
                ('buyum_fotosurati', models.TextField(blank=True, null=True)),
                ('shaxs_turi', models.CharField(choices=[('jismoniy', 'Jismoniy Shaxs'), ('yuridik', 'Yuridik Shaxs')], max_length=10)),
                ('xususiyatlari', models.CharField(blank=True, max_length=255, null=True)),
                ('ishlab_chiqarilgan_yili', models.CharField(max_length=4)),
                ('ishlab_chiqarilgan_davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.davlat')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guruhgaoid')),
                ('jismoniy_shaxs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jismoniyshaxs')),
                ('nomlanishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nomlanishi')),
                ('rangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rangi')),
                ('rusumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rusumi')),
                ('yuridik_shaxs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.yuridikshaxs')),
            ],
        ),
    ]
