# Generated by Django 5.1.3 on 2025-02-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Davlati',
        ),
    ]
