# Generated by Django 5.1.3 on 2025-02-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_davlati'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetelsName',
        ),
    ]
