# Generated by Django 5.1.3 on 2025-02-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_detelsname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sababi',
        ),
    ]
