# Generated by Django 5.1.6 on 2025-02-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_sababi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyuminfo',
            name='xususiyatlari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.xususiyatlari'),
            preserve_default=False,
        ),
    ]
